### ISSUE TITLE
No License specified

### ISSUE THREAD

**Issue by Empiire00** [Gruntfuggly/gerrit-view#21]
Hi, 
I wanted to fork your project for development, but you did not specify any License in your project. 
Am I allowed to use your code and/or are you able to specify a license?
Thanks in advance.

**Comment by Gruntfuggly** [comment]
Hi - feel free to fork. I've sort of abandoned it as I no longer have access to a Gerrit server (I previously used it in my day job).

Good luck!

**Comment by Empiire00** [comment]
Hi,
Would it be possible for you to provide a license(e.g. Apache 2.0) in this repository?
