### ISSUE TITLE
permit to set username in ssh

### ISSUE THREAD

**Issue by nicola-lunghi** [Gruntfuggly/gerrit-view#5]
Hi,

for now the ssh connect is setting the username to os.userInfo().username
can you add a field to set the username? (I'm a terrible js programmer) 

```
 ssh.connect( {
            host: query.server,
            username: os.userInfo().username,
            port: query.port,
            privateKey: query.keyFile
        } ).then( function()
```

**Comment by Gruntfuggly** [comment]
I've just uploaded a version which allows the username to be changed. It also now defaults to lowercase (in case that was what was causing your issue!).
